# Generated by Django 4.2.6 on 2023-10-08 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelPeligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('color', models.CharField(max_length=100)),
                ('infoAnimal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animales.infoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('infoAnimal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animales.infoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('infoAnimal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animales.infoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenada', models.CharField(max_length=100)),
                ('infoAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.infoanimal')),
            ],
        ),
    ]
