# Generated by Django 4.2.6 on 2023-10-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_remove_coordenadas_coordenada_coordenadas_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.TextField()),
                ('modeloAr', models.CharField(max_length=200)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos/')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.multimediaanimal')),
            ],
        ),
    ]
