# Generated by Django 4.2.6 on 2023-10-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_multimediaanimal_imagenanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediaanimal',
            name='animal',
            field=models.OneToOneField(default=1.222, on_delete=django.db.models.deletion.CASCADE, to='animales.animal'),
            preserve_default=False,
        ),
    ]
