# Generated by Django 4.2.6 on 2023-10-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0005_multimediaanimal_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenadas',
            name='infoAnimal',
        ),
        migrations.RemoveField(
            model_name='habitat',
            name='infoAnimal',
        ),
        migrations.AddField(
            model_name='coordenadas',
            name='animal',
            field=models.ForeignKey(default=2.3, on_delete=django.db.models.deletion.CASCADE, to='animales.animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitat',
            name='animal',
            field=models.OneToOneField(default=2.3, on_delete=django.db.models.deletion.CASCADE, to='animales.animal'),
            preserve_default=False,
        ),
    ]
