# Generated by Django 4.2.6 on 2023-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_remove_coordenadas_infoanimal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediaanimal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.DeleteModel(
            name='ImagenAnimal',
        ),
    ]
