# Generated by Django 4.2.6 on 2023-10-08 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animales', '0007_multimediaanimal_imagen_delete_imagenanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
