# Generated by Django 4.2.6 on 2023-10-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_multimediausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediausuario',
            name='imagenPerfil',
            field=models.ImageField(blank=True, default='perfil/default.jpg', null=True, upload_to='perfil/'),
        ),
    ]
